#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana07Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="neptuno")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertclientes(clientes instance);
    partial void Updateclientes(clientes instance);
    partial void Deleteclientes(clientes instance);
    partial void InsertPedidos(Pedidos instance);
    partial void UpdatePedidos(Pedidos instance);
    partial void DeletePedidos(Pedidos instance);
    partial void Insertproveedores(proveedores instance);
    partial void Updateproveedores(proveedores instance);
    partial void Deleteproveedores(proveedores instance);
    partial void Insertproductos(productos instance);
    partial void Updateproductos(productos instance);
    partial void Deleteproductos(productos instance);
    partial void Insertcategorias(categorias instance);
    partial void Updatecategorias(categorias instance);
    partial void Deletecategorias(categorias instance);
    partial void InsertEmpleados(Empleados instance);
    partial void UpdateEmpleados(Empleados instance);
    partial void DeleteEmpleados(Empleados instance);
    partial void Insertcompañiasdeenvios(compañiasdeenvios instance);
    partial void Updatecompañiasdeenvios(compañiasdeenvios instance);
    partial void Deletecompañiasdeenvios(compañiasdeenvios instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::Semana07Linq.Properties.Settings.Default.neptunoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<clientes> clientes
		{
			get
			{
				return this.GetTable<clientes>();
			}
		}
		
		public System.Data.Linq.Table<Pedidos> Pedidos
		{
			get
			{
				return this.GetTable<Pedidos>();
			}
		}
		
		public System.Data.Linq.Table<detallesdepedidos> detallesdepedidos
		{
			get
			{
				return this.GetTable<detallesdepedidos>();
			}
		}
		
		public System.Data.Linq.Table<proveedores> proveedores
		{
			get
			{
				return this.GetTable<proveedores>();
			}
		}
		
		public System.Data.Linq.Table<productos> productos
		{
			get
			{
				return this.GetTable<productos>();
			}
		}
		
		public System.Data.Linq.Table<categorias> categorias
		{
			get
			{
				return this.GetTable<categorias>();
			}
		}
		
		public System.Data.Linq.Table<Empleados> Empleados
		{
			get
			{
				return this.GetTable<Empleados>();
			}
		}
		
		public System.Data.Linq.Table<compañiasdeenvios> compañiasdeenvios
		{
			get
			{
				return this.GetTable<compañiasdeenvios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idCliente;
		
		private string _NombreCompañia;
		
		private string _NombreContacto;
		
		private string _CargoContacto;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Region;
		
		private string _CodPostal;
		
		private string _Pais;
		
		private string _Telefono;
		
		private string _Fax;
		
		private EntitySet<Pedidos> _Pedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(string value);
    partial void OnidClienteChanged();
    partial void OnNombreCompañiaChanging(string value);
    partial void OnNombreCompañiaChanged();
    partial void OnNombreContactoChanging(string value);
    partial void OnNombreContactoChanged();
    partial void OnCargoContactoChanging(string value);
    partial void OnCargoContactoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnCodPostalChanging(string value);
    partial void OnCodPostalChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public clientes()
		{
			this._Pedidos = new EntitySet<Pedidos>(new Action<Pedidos>(this.attach_Pedidos), new Action<Pedidos>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompañia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreCompañia
		{
			get
			{
				return this._NombreCompañia;
			}
			set
			{
				if ((this._NombreCompañia != value))
				{
					this.OnNombreCompañiaChanging(value);
					this.SendPropertyChanging();
					this._NombreCompañia = value;
					this.SendPropertyChanged("NombreCompañia");
					this.OnNombreCompañiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="VarChar(100)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this.OnNombreContactoChanging(value);
					this.SendPropertyChanging();
					this._NombreContacto = value;
					this.SendPropertyChanged("NombreContacto");
					this.OnNombreContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoContacto", DbType="VarChar(100)")]
		public string CargoContacto
		{
			get
			{
				return this._CargoContacto;
			}
			set
			{
				if ((this._CargoContacto != value))
				{
					this.OnCargoContactoChanging(value);
					this.SendPropertyChanging();
					this._CargoContacto = value;
					this.SendPropertyChanged("CargoContacto");
					this.OnCargoContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(100)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="VarChar(100)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPostal", DbType="VarChar(100)")]
		public string CodPostal
		{
			get
			{
				return this._CodPostal;
			}
			set
			{
				if ((this._CodPostal != value))
				{
					this.OnCodPostalChanging(value);
					this.SendPropertyChanging();
					this._CodPostal = value;
					this.SendPropertyChanged("CodPostal");
					this.OnCodPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(100)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(30)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(30)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="clientes_Pedidos", Storage="_Pedidos", ThisKey="idCliente", OtherKey="IdCliente")]
		public EntitySet<Pedidos> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.clientes = this;
		}
		
		private void detach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedidos")]
	public partial class Pedidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPedido;
		
		private string _IdCliente;
		
		private int _IdEmpleado;
		
		private System.Nullable<System.DateTime> _FechaPedido;
		
		private System.Nullable<System.DateTime> _FechaEntrega;
		
		private System.Nullable<System.DateTime> _FechaEnvio;
		
		private System.Nullable<int> _FormaEnvio;
		
		private System.Nullable<decimal> _Cargo;
		
		private string _Destinatario;
		
		private string _DireccionDestinatario;
		
		private string _CiudadDestinatario;
		
		private string _RegionDestinatario;
		
		private string _CodPostalDestinatario;
		
		private string _PaisDestinatario;
		
		private EntityRef<clientes> _clientes;
		
		private EntityRef<Empleados> _Empleados;
		
		private EntityRef<compañiasdeenvios> _compañiasdeenvios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPedidoChanging(int value);
    partial void OnIdPedidoChanged();
    partial void OnIdClienteChanging(string value);
    partial void OnIdClienteChanged();
    partial void OnIdEmpleadoChanging(int value);
    partial void OnIdEmpleadoChanged();
    partial void OnFechaPedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaPedidoChanged();
    partial void OnFechaEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEntregaChanged();
    partial void OnFechaEnvioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEnvioChanged();
    partial void OnFormaEnvioChanging(System.Nullable<int> value);
    partial void OnFormaEnvioChanged();
    partial void OnCargoChanging(System.Nullable<decimal> value);
    partial void OnCargoChanged();
    partial void OnDestinatarioChanging(string value);
    partial void OnDestinatarioChanged();
    partial void OnDireccionDestinatarioChanging(string value);
    partial void OnDireccionDestinatarioChanged();
    partial void OnCiudadDestinatarioChanging(string value);
    partial void OnCiudadDestinatarioChanged();
    partial void OnRegionDestinatarioChanging(string value);
    partial void OnRegionDestinatarioChanged();
    partial void OnCodPostalDestinatarioChanging(string value);
    partial void OnCodPostalDestinatarioChanged();
    partial void OnPaisDestinatarioChanging(string value);
    partial void OnPaisDestinatarioChanged();
    #endregion
		
		public Pedidos()
		{
			this._clientes = default(EntityRef<clientes>);
			this._Empleados = default(EntityRef<Empleados>);
			this._compañiasdeenvios = default(EntityRef<compañiasdeenvios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", DbType="Int NOT NULL")]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					if (this._Empleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdEmpleado = value;
					this.SendPropertyChanged("IdEmpleado");
					this.OnIdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPedido", DbType="Date")]
		public System.Nullable<System.DateTime> FechaPedido
		{
			get
			{
				return this._FechaPedido;
			}
			set
			{
				if ((this._FechaPedido != value))
				{
					this.OnFechaPedidoChanging(value);
					this.SendPropertyChanging();
					this._FechaPedido = value;
					this.SendPropertyChanged("FechaPedido");
					this.OnFechaPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrega", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntrega
		{
			get
			{
				return this._FechaEntrega;
			}
			set
			{
				if ((this._FechaEntrega != value))
				{
					this.OnFechaEntregaChanging(value);
					this.SendPropertyChanging();
					this._FechaEntrega = value;
					this.SendPropertyChanged("FechaEntrega");
					this.OnFechaEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this.OnFechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaEnvio = value;
					this.SendPropertyChanged("FechaEnvio");
					this.OnFechaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaEnvio", DbType="Int")]
		public System.Nullable<int> FormaEnvio
		{
			get
			{
				return this._FormaEnvio;
			}
			set
			{
				if ((this._FormaEnvio != value))
				{
					if (this._compañiasdeenvios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFormaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FormaEnvio = value;
					this.SendPropertyChanged("FormaEnvio");
					this.OnFormaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destinatario", DbType="VarChar(60)")]
		public string Destinatario
		{
			get
			{
				return this._Destinatario;
			}
			set
			{
				if ((this._Destinatario != value))
				{
					this.OnDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._Destinatario = value;
					this.SendPropertyChanged("Destinatario");
					this.OnDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionDestinatario", DbType="VarChar(60)")]
		public string DireccionDestinatario
		{
			get
			{
				return this._DireccionDestinatario;
			}
			set
			{
				if ((this._DireccionDestinatario != value))
				{
					this.OnDireccionDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._DireccionDestinatario = value;
					this.SendPropertyChanged("DireccionDestinatario");
					this.OnDireccionDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadDestinatario", DbType="VarChar(60)")]
		public string CiudadDestinatario
		{
			get
			{
				return this._CiudadDestinatario;
			}
			set
			{
				if ((this._CiudadDestinatario != value))
				{
					this.OnCiudadDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._CiudadDestinatario = value;
					this.SendPropertyChanged("CiudadDestinatario");
					this.OnCiudadDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionDestinatario", DbType="VarChar(60)")]
		public string RegionDestinatario
		{
			get
			{
				return this._RegionDestinatario;
			}
			set
			{
				if ((this._RegionDestinatario != value))
				{
					this.OnRegionDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._RegionDestinatario = value;
					this.SendPropertyChanged("RegionDestinatario");
					this.OnRegionDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPostalDestinatario", DbType="VarChar(60)")]
		public string CodPostalDestinatario
		{
			get
			{
				return this._CodPostalDestinatario;
			}
			set
			{
				if ((this._CodPostalDestinatario != value))
				{
					this.OnCodPostalDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._CodPostalDestinatario = value;
					this.SendPropertyChanged("CodPostalDestinatario");
					this.OnCodPostalDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisDestinatario", DbType="VarChar(60)")]
		public string PaisDestinatario
		{
			get
			{
				return this._PaisDestinatario;
			}
			set
			{
				if ((this._PaisDestinatario != value))
				{
					this.OnPaisDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._PaisDestinatario = value;
					this.SendPropertyChanged("PaisDestinatario");
					this.OnPaisDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="clientes_Pedidos", Storage="_clientes", ThisKey="IdCliente", OtherKey="idCliente", IsForeignKey=true)]
		public clientes clientes
		{
			get
			{
				return this._clientes.Entity;
			}
			set
			{
				clientes previousValue = this._clientes.Entity;
				if (((previousValue != value) 
							|| (this._clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._clientes.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._clientes.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._IdCliente = value.idCliente;
					}
					else
					{
						this._IdCliente = default(string);
					}
					this.SendPropertyChanged("clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Pedidos", Storage="_Empleados", ThisKey="IdEmpleado", OtherKey="IdEmpleado", IsForeignKey=true)]
		public Empleados Empleados
		{
			get
			{
				return this._Empleados.Entity;
			}
			set
			{
				Empleados previousValue = this._Empleados.Entity;
				if (((previousValue != value) 
							|| (this._Empleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleados.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Empleados.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._IdEmpleado = value.IdEmpleado;
					}
					else
					{
						this._IdEmpleado = default(int);
					}
					this.SendPropertyChanged("Empleados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compañiasdeenvios_Pedidos", Storage="_compañiasdeenvios", ThisKey="FormaEnvio", OtherKey="idCompañiaEnvios", IsForeignKey=true)]
		public compañiasdeenvios compañiasdeenvios
		{
			get
			{
				return this._compañiasdeenvios.Entity;
			}
			set
			{
				compañiasdeenvios previousValue = this._compañiasdeenvios.Entity;
				if (((previousValue != value) 
							|| (this._compañiasdeenvios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._compañiasdeenvios.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._compañiasdeenvios.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._FormaEnvio = value.idCompañiaEnvios;
					}
					else
					{
						this._FormaEnvio = default(Nullable<int>);
					}
					this.SendPropertyChanged("compañiasdeenvios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detallesdepedidos")]
	public partial class detallesdepedidos
	{
		
		private System.Nullable<int> _idpedido;
		
		private System.Nullable<int> _idproducto;
		
		private decimal _preciounidad;
		
		private int _cantidad;
		
		private decimal _descuento;
		
		public detallesdepedidos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpedido", DbType="Int")]
		public System.Nullable<int> idpedido
		{
			get
			{
				return this._idpedido;
			}
			set
			{
				if ((this._idpedido != value))
				{
					this._idpedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idproducto", DbType="Int")]
		public System.Nullable<int> idproducto
		{
			get
			{
				return this._idproducto;
			}
			set
			{
				if ((this._idproducto != value))
				{
					this._idproducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preciounidad", DbType="Decimal(18,0) NOT NULL")]
		public decimal preciounidad
		{
			get
			{
				return this._preciounidad;
			}
			set
			{
				if ((this._preciounidad != value))
				{
					this._preciounidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="Decimal(18,0) NOT NULL")]
		public decimal descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this._descuento = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proveedores")]
	public partial class proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProveedor;
		
		private string _nombreCompañia;
		
		private string _nombrecontacto;
		
		private string _cargocontacto;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _region;
		
		private string _codPostal;
		
		private string _pais;
		
		private string _telefono;
		
		private string _fax;
		
		private string _paginaprincipal;
		
		private EntitySet<productos> _productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProveedorChanging(int value);
    partial void OnidProveedorChanged();
    partial void OnnombreCompañiaChanging(string value);
    partial void OnnombreCompañiaChanged();
    partial void OnnombrecontactoChanging(string value);
    partial void OnnombrecontactoChanged();
    partial void OncargocontactoChanging(string value);
    partial void OncargocontactoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncodPostalChanging(string value);
    partial void OncodPostalChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnpaginaprincipalChanging(string value);
    partial void OnpaginaprincipalChanged();
    #endregion
		
		public proveedores()
		{
			this._productos = new EntitySet<productos>(new Action<productos>(this.attach_productos), new Action<productos>(this.detach_productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idProveedor
		{
			get
			{
				return this._idProveedor;
			}
			set
			{
				if ((this._idProveedor != value))
				{
					this.OnidProveedorChanging(value);
					this.SendPropertyChanging();
					this._idProveedor = value;
					this.SendPropertyChanged("idProveedor");
					this.OnidProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCompañia", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombreCompañia
		{
			get
			{
				return this._nombreCompañia;
			}
			set
			{
				if ((this._nombreCompañia != value))
				{
					this.OnnombreCompañiaChanging(value);
					this.SendPropertyChanging();
					this._nombreCompañia = value;
					this.SendPropertyChanged("nombreCompañia");
					this.OnnombreCompañiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecontacto", DbType="VarChar(30)")]
		public string nombrecontacto
		{
			get
			{
				return this._nombrecontacto;
			}
			set
			{
				if ((this._nombrecontacto != value))
				{
					this.OnnombrecontactoChanging(value);
					this.SendPropertyChanging();
					this._nombrecontacto = value;
					this.SendPropertyChanged("nombrecontacto");
					this.OnnombrecontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargocontacto", DbType="VarChar(30)")]
		public string cargocontacto
		{
			get
			{
				return this._cargocontacto;
			}
			set
			{
				if ((this._cargocontacto != value))
				{
					this.OncargocontactoChanging(value);
					this.SendPropertyChanging();
					this._cargocontacto = value;
					this.SendPropertyChanged("cargocontacto");
					this.OncargocontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(60)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(15)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(15)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPostal", DbType="VarChar(10)")]
		public string codPostal
		{
			get
			{
				return this._codPostal;
			}
			set
			{
				if ((this._codPostal != value))
				{
					this.OncodPostalChanging(value);
					this.SendPropertyChanging();
					this._codPostal = value;
					this.SendPropertyChanged("codPostal");
					this.OncodPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(15)")]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(24)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(24)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paginaprincipal", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string paginaprincipal
		{
			get
			{
				return this._paginaprincipal;
			}
			set
			{
				if ((this._paginaprincipal != value))
				{
					this.OnpaginaprincipalChanging(value);
					this.SendPropertyChanging();
					this._paginaprincipal = value;
					this.SendPropertyChanged("paginaprincipal");
					this.OnpaginaprincipalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_productos", Storage="_productos", ThisKey="idProveedor", OtherKey="idProveedor")]
		public EntitySet<productos> productos
		{
			get
			{
				return this._productos;
			}
			set
			{
				this._productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_productos(productos entity)
		{
			this.SendPropertyChanging();
			entity.proveedores = this;
		}
		
		private void detach_productos(productos entity)
		{
			this.SendPropertyChanging();
			entity.proveedores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productos")]
	public partial class productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idproducto;
		
		private string _nombreProducto;
		
		private System.Nullable<int> _idProveedor;
		
		private System.Nullable<int> _idCategoria;
		
		private string _cantidadPorUnidad;
		
		private System.Nullable<decimal> _precioUnidad;
		
		private System.Nullable<short> _unidadesEnExistencia;
		
		private System.Nullable<short> _unidadesEnPedido;
		
		private System.Nullable<short> _nivelNuevoPedido;
		
		private System.Nullable<short> _suspendido;
		
		private string _categoriaProducto;
		
		private EntityRef<proveedores> _proveedores;
		
		private EntityRef<categorias> _categorias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidproductoChanging(int value);
    partial void OnidproductoChanged();
    partial void OnnombreProductoChanging(string value);
    partial void OnnombreProductoChanged();
    partial void OnidProveedorChanging(System.Nullable<int> value);
    partial void OnidProveedorChanged();
    partial void OnidCategoriaChanging(System.Nullable<int> value);
    partial void OnidCategoriaChanged();
    partial void OncantidadPorUnidadChanging(string value);
    partial void OncantidadPorUnidadChanged();
    partial void OnprecioUnidadChanging(System.Nullable<decimal> value);
    partial void OnprecioUnidadChanged();
    partial void OnunidadesEnExistenciaChanging(System.Nullable<short> value);
    partial void OnunidadesEnExistenciaChanged();
    partial void OnunidadesEnPedidoChanging(System.Nullable<short> value);
    partial void OnunidadesEnPedidoChanged();
    partial void OnnivelNuevoPedidoChanging(System.Nullable<short> value);
    partial void OnnivelNuevoPedidoChanged();
    partial void OnsuspendidoChanging(System.Nullable<short> value);
    partial void OnsuspendidoChanged();
    partial void OncategoriaProductoChanging(string value);
    partial void OncategoriaProductoChanged();
    #endregion
		
		public productos()
		{
			this._proveedores = default(EntityRef<proveedores>);
			this._categorias = default(EntityRef<categorias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idproducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idproducto
		{
			get
			{
				return this._idproducto;
			}
			set
			{
				if ((this._idproducto != value))
				{
					this.OnidproductoChanging(value);
					this.SendPropertyChanging();
					this._idproducto = value;
					this.SendPropertyChanged("idproducto");
					this.OnidproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(40)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this.OnnombreProductoChanging(value);
					this.SendPropertyChanging();
					this._nombreProducto = value;
					this.SendPropertyChanged("nombreProducto");
					this.OnnombreProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="Int")]
		public System.Nullable<int> idProveedor
		{
			get
			{
				return this._idProveedor;
			}
			set
			{
				if ((this._idProveedor != value))
				{
					if (this._proveedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProveedorChanging(value);
					this.SendPropertyChanging();
					this._idProveedor = value;
					this.SendPropertyChanged("idProveedor");
					this.OnidProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int")]
		public System.Nullable<int> idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					if (this._categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadPorUnidad", DbType="VarChar(20)")]
		public string cantidadPorUnidad
		{
			get
			{
				return this._cantidadPorUnidad;
			}
			set
			{
				if ((this._cantidadPorUnidad != value))
				{
					this.OncantidadPorUnidadChanging(value);
					this.SendPropertyChanging();
					this._cantidadPorUnidad = value;
					this.SendPropertyChanged("cantidadPorUnidad");
					this.OncantidadPorUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioUnidad", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precioUnidad
		{
			get
			{
				return this._precioUnidad;
			}
			set
			{
				if ((this._precioUnidad != value))
				{
					this.OnprecioUnidadChanging(value);
					this.SendPropertyChanging();
					this._precioUnidad = value;
					this.SendPropertyChanged("precioUnidad");
					this.OnprecioUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidadesEnExistencia", DbType="SmallInt")]
		public System.Nullable<short> unidadesEnExistencia
		{
			get
			{
				return this._unidadesEnExistencia;
			}
			set
			{
				if ((this._unidadesEnExistencia != value))
				{
					this.OnunidadesEnExistenciaChanging(value);
					this.SendPropertyChanging();
					this._unidadesEnExistencia = value;
					this.SendPropertyChanged("unidadesEnExistencia");
					this.OnunidadesEnExistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidadesEnPedido", DbType="SmallInt")]
		public System.Nullable<short> unidadesEnPedido
		{
			get
			{
				return this._unidadesEnPedido;
			}
			set
			{
				if ((this._unidadesEnPedido != value))
				{
					this.OnunidadesEnPedidoChanging(value);
					this.SendPropertyChanging();
					this._unidadesEnPedido = value;
					this.SendPropertyChanged("unidadesEnPedido");
					this.OnunidadesEnPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivelNuevoPedido", DbType="SmallInt")]
		public System.Nullable<short> nivelNuevoPedido
		{
			get
			{
				return this._nivelNuevoPedido;
			}
			set
			{
				if ((this._nivelNuevoPedido != value))
				{
					this.OnnivelNuevoPedidoChanging(value);
					this.SendPropertyChanging();
					this._nivelNuevoPedido = value;
					this.SendPropertyChanged("nivelNuevoPedido");
					this.OnnivelNuevoPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspendido", DbType="SmallInt")]
		public System.Nullable<short> suspendido
		{
			get
			{
				return this._suspendido;
			}
			set
			{
				if ((this._suspendido != value))
				{
					this.OnsuspendidoChanging(value);
					this.SendPropertyChanging();
					this._suspendido = value;
					this.SendPropertyChanged("suspendido");
					this.OnsuspendidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoriaProducto", DbType="VarChar(20)")]
		public string categoriaProducto
		{
			get
			{
				return this._categoriaProducto;
			}
			set
			{
				if ((this._categoriaProducto != value))
				{
					this.OncategoriaProductoChanging(value);
					this.SendPropertyChanging();
					this._categoriaProducto = value;
					this.SendPropertyChanged("categoriaProducto");
					this.OncategoriaProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_productos", Storage="_proveedores", ThisKey="idProveedor", OtherKey="idProveedor", IsForeignKey=true)]
		public proveedores proveedores
		{
			get
			{
				return this._proveedores.Entity;
			}
			set
			{
				proveedores previousValue = this._proveedores.Entity;
				if (((previousValue != value) 
							|| (this._proveedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._proveedores.Entity = null;
						previousValue.productos.Remove(this);
					}
					this._proveedores.Entity = value;
					if ((value != null))
					{
						value.productos.Add(this);
						this._idProveedor = value.idProveedor;
					}
					else
					{
						this._idProveedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("proveedores");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categorias_productos", Storage="_categorias", ThisKey="idCategoria", OtherKey="idcategoria", IsForeignKey=true)]
		public categorias categorias
		{
			get
			{
				return this._categorias.Entity;
			}
			set
			{
				categorias previousValue = this._categorias.Entity;
				if (((previousValue != value) 
							|| (this._categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categorias.Entity = null;
						previousValue.productos.Remove(this);
					}
					this._categorias.Entity = value;
					if ((value != null))
					{
						value.productos.Add(this);
						this._idCategoria = value.idcategoria;
					}
					else
					{
						this._idCategoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("categorias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categorias")]
	public partial class categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcategoria;
		
		private string _nombrecategoria;
		
		private string _descripcion;
		
		private System.Nullable<bool> _activo;
		
		private EntitySet<productos> _productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcategoriaChanging(int value);
    partial void OnidcategoriaChanged();
    partial void OnnombrecategoriaChanging(string value);
    partial void OnnombrecategoriaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    #endregion
		
		public categorias()
		{
			this._productos = new EntitySet<productos>(new Action<productos>(this.attach_productos), new Action<productos>(this.detach_productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					this.OnidcategoriaChanging(value);
					this.SendPropertyChanging();
					this._idcategoria = value;
					this.SendPropertyChanged("idcategoria");
					this.OnidcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrecategoria
		{
			get
			{
				return this._nombrecategoria;
			}
			set
			{
				if ((this._nombrecategoria != value))
				{
					this.OnnombrecategoriaChanging(value);
					this.SendPropertyChanging();
					this._nombrecategoria = value;
					this.SendPropertyChanged("nombrecategoria");
					this.OnnombrecategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categorias_productos", Storage="_productos", ThisKey="idcategoria", OtherKey="idCategoria")]
		public EntitySet<productos> productos
		{
			get
			{
				return this._productos;
			}
			set
			{
				this._productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_productos(productos entity)
		{
			this.SendPropertyChanging();
			entity.categorias = this;
		}
		
		private void detach_productos(productos entity)
		{
			this.SendPropertyChanging();
			entity.categorias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpleado;
		
		private string _Apellidos;
		
		private string _Nombre;
		
		private string _cargo;
		
		private string _Tratamiento;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private System.Nullable<System.DateTime> _FechaContratacion;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _region;
		
		private string _codPostal;
		
		private string _pais;
		
		private string _TelDomicilio;
		
		private string _Extension;
		
		private string _notas;
		
		private System.Nullable<int> _Jefe;
		
		private System.Nullable<decimal> _sueldoBasico;
		
		private EntitySet<Pedidos> _Pedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpleadoChanging(int value);
    partial void OnIdEmpleadoChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OncargoChanging(string value);
    partial void OncargoChanged();
    partial void OnTratamientoChanging(string value);
    partial void OnTratamientoChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnFechaContratacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaContratacionChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncodPostalChanging(string value);
    partial void OncodPostalChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void OnTelDomicilioChanging(string value);
    partial void OnTelDomicilioChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnnotasChanging(string value);
    partial void OnnotasChanged();
    partial void OnJefeChanging(System.Nullable<int> value);
    partial void OnJefeChanged();
    partial void OnsueldoBasicoChanging(System.Nullable<decimal> value);
    partial void OnsueldoBasicoChanged();
    #endregion
		
		public Empleados()
		{
			this._Pedidos = new EntitySet<Pedidos>(new Action<Pedidos>(this.attach_Pedidos), new Action<Pedidos>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this.OnIdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdEmpleado = value;
					this.SendPropertyChanged("IdEmpleado");
					this.OnIdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(20)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(40)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this.OncargoChanging(value);
					this.SendPropertyChanging();
					this._cargo = value;
					this.SendPropertyChanged("cargo");
					this.OncargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tratamiento", DbType="VarChar(40)")]
		public string Tratamiento
		{
			get
			{
				return this._Tratamiento;
			}
			set
			{
				if ((this._Tratamiento != value))
				{
					this.OnTratamientoChanging(value);
					this.SendPropertyChanging();
					this._Tratamiento = value;
					this.SendPropertyChanged("Tratamiento");
					this.OnTratamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaContratacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaContratacion
		{
			get
			{
				return this._FechaContratacion;
			}
			set
			{
				if ((this._FechaContratacion != value))
				{
					this.OnFechaContratacionChanging(value);
					this.SendPropertyChanging();
					this._FechaContratacion = value;
					this.SendPropertyChanged("FechaContratacion");
					this.OnFechaContratacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(60)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(15)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(15)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPostal", DbType="VarChar(10)")]
		public string codPostal
		{
			get
			{
				return this._codPostal;
			}
			set
			{
				if ((this._codPostal != value))
				{
					this.OncodPostalChanging(value);
					this.SendPropertyChanging();
					this._codPostal = value;
					this.SendPropertyChanged("codPostal");
					this.OncodPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(15)")]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelDomicilio", DbType="VarChar(24)")]
		public string TelDomicilio
		{
			get
			{
				return this._TelDomicilio;
			}
			set
			{
				if ((this._TelDomicilio != value))
				{
					this.OnTelDomicilioChanging(value);
					this.SendPropertyChanging();
					this._TelDomicilio = value;
					this.SendPropertyChanged("TelDomicilio");
					this.OnTelDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="VarChar(4)")]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notas", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string notas
		{
			get
			{
				return this._notas;
			}
			set
			{
				if ((this._notas != value))
				{
					this.OnnotasChanging(value);
					this.SendPropertyChanging();
					this._notas = value;
					this.SendPropertyChanged("notas");
					this.OnnotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jefe", DbType="Int")]
		public System.Nullable<int> Jefe
		{
			get
			{
				return this._Jefe;
			}
			set
			{
				if ((this._Jefe != value))
				{
					this.OnJefeChanging(value);
					this.SendPropertyChanging();
					this._Jefe = value;
					this.SendPropertyChanged("Jefe");
					this.OnJefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sueldoBasico", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sueldoBasico
		{
			get
			{
				return this._sueldoBasico;
			}
			set
			{
				if ((this._sueldoBasico != value))
				{
					this.OnsueldoBasicoChanging(value);
					this.SendPropertyChanging();
					this._sueldoBasico = value;
					this.SendPropertyChanged("sueldoBasico");
					this.OnsueldoBasicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Pedidos", Storage="_Pedidos", ThisKey="IdEmpleado", OtherKey="IdEmpleado")]
		public EntitySet<Pedidos> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = this;
		}
		
		private void detach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compañiasdeenvios")]
	public partial class compañiasdeenvios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCompañiaEnvios;
		
		private string _nombreCompañia;
		
		private string _telefono;
		
		private EntitySet<Pedidos> _Pedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCompañiaEnviosChanging(int value);
    partial void OnidCompañiaEnviosChanged();
    partial void OnnombreCompañiaChanging(string value);
    partial void OnnombreCompañiaChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    #endregion
		
		public compañiasdeenvios()
		{
			this._Pedidos = new EntitySet<Pedidos>(new Action<Pedidos>(this.attach_Pedidos), new Action<Pedidos>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCompañiaEnvios", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCompañiaEnvios
		{
			get
			{
				return this._idCompañiaEnvios;
			}
			set
			{
				if ((this._idCompañiaEnvios != value))
				{
					this.OnidCompañiaEnviosChanging(value);
					this.SendPropertyChanging();
					this._idCompañiaEnvios = value;
					this.SendPropertyChanged("idCompañiaEnvios");
					this.OnidCompañiaEnviosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCompañia", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombreCompañia
		{
			get
			{
				return this._nombreCompañia;
			}
			set
			{
				if ((this._nombreCompañia != value))
				{
					this.OnnombreCompañiaChanging(value);
					this.SendPropertyChanging();
					this._nombreCompañia = value;
					this.SendPropertyChanged("nombreCompañia");
					this.OnnombreCompañiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(24)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compañiasdeenvios_Pedidos", Storage="_Pedidos", ThisKey="idCompañiaEnvios", OtherKey="FormaEnvio")]
		public EntitySet<Pedidos> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.compañiasdeenvios = this;
		}
		
		private void detach_Pedidos(Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.compañiasdeenvios = null;
		}
	}
}
#pragma warning restore 1591
